import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "remixicon/fonts/remixicon.css";
import { Toaster } from "sonner";
import Navbar from "../components/sections/Navbar";
import LenisProvider from "../Providers/LenisProvider";
import "./globals.css";
import Footer from "../components/sections/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gallant Knight Manufacturing Corp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider>

          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </LenisProvider>
      </body>
    </html>
  );
}
